### ISSUE TITLE
Can not import version 1.x models using Import JSON feature

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#512]
**Describe the bug**
A version 1.x threat model can not be imported using the JSON Import feature on the home page. Version 2.0 threat models can be imported OK

**Expected behaviour**
Paste a version 1.x threat model into the JSON Import text area. Threat model should be accepted OK

**Environment**
 - Version: 2.0
 - Platform: both Web App / Desktop App
 - OS: any MacOS / Windows / Linux
 - Browser: any chrome, firefox, safari

**To Reproduce**
* Login to a local session
* paste the following version 2.0 model into the JSON Import text area
```
{
  "version": "2.0",
  "summary":{
    "title":"New threat model"
  },
  "detail":{
    "contributors":[],
    "diagrams":[]
  }
}
```
* the threat model is accepted
* paste the following version 1.x model into the JSON Import text area
```
{
  "summary": {
    "title":"New threat model"
  },
  "detail": {
    "contributors": [],
    "diagrams": []
  }
}
```
* the application hangs with a console error

**Any additional context, screenshots, etc**
throwing a navigation guard error on a version 1.x import:

```
vue-router.esm.js:2065 Uncaught (in promise) Error: Redirected when going from "/local/threatmodel/import" to "/local/New%20threat%20model" via a navigation guard.
    at createRouterError (vue-router.esm.js:2065:1)
    at createNavigationRedirectedError (vue-router.esm.js:2024:1)
    at vue-router.esm.js:2376:1
    at upgradeGuard (index.js:49:16)
    at iterator (vue-router.esm.js:2362:1)
    at step (vue-router.esm.js:2004:1)
    at step (vue-router.esm.js:2008:1)
    at runQueue (vue-router.esm.js:2012:1)
    at HashHistory.confirmTransition (vue-router.esm.js:2392:1)
    at HashHistory.transitionTo (vue-router.esm.js:2260:1)
```

**Comment by jgadsden** [comment]
This is probably linked to issue #378

**Comment by jgadsden** [comment]
The navigation guard error is not the cause - it is just a feature of vue-router and can be ignored:
https://stackoverflow.com/questions/62223195/vue-router-uncaught-in-promise-error-redirected-from-login-to-via-a

**Comment by jgadsden** [comment]
This is a duplicate of #378 "New Threat Model Gets Stuck at v2 Welcome"
