### ISSUE TITLE
Catch more errors

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#68]
**Describe what problem your feature request solves**
Some errors are not caught, and the resulting trace output is not easy to recover from

**Describe the solution you'd like**
Catch errors so that the browser does not display trace, and the app still runs

**Additional context**
Here is a login error (I was messing with github client secret env var):
```
TokenError: The client_id and/or client_secret passed are incorrect.
    at Strategy.OAuth2Strategy.parseErrorResponse (node_modules/passport-oauth2/lib/strategy.js:358:12)
    at Strategy.OAuth2Strategy._createOAuthError (node_modules/passport-oauth2/lib/strategy.js:405:16)
    at node_modules/passport-oauth2/lib/strategy.js:175:45
    at node_modules/passport-github/lib/strategy.js:77:16
    at node_modules/oauth/lib/oauth2.js:209:7
    at passBackControl (node_modules/oauth/lib/oauth2.js:134:9)
    at IncomingMessage.<anonymous> (node_modules/oauth/lib/oauth2.js:157:7)
    at IncomingMessage.emit (node:events:390:22)
    at endReadableNT (node:internal/streams/readable:1307:12)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)
```
and another one where I was messing with CSRF:
```
ForbiddenError: invalid csrf token
    at csrf (node_modules/csurf/index.js:112:19)
    at Layer.handle [as handle_request] (node_modules/express/lib/router/layer.js:95:5)
    at next (node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (node_modules/express/lib/router/layer.js:95:5)
    at node_modules/express/lib/router/index.js:281:22
    at Function.process_params (node_modules/express/lib/router/index.js:335:12)
    at next (/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (node_modules/express/lib/router/index.js:174:3)
    at router (node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (node_modules/express/lib/router/index.js:317:13)
    at node_modules/express/lib/router/index.js:284:7
    at Function.process_params (node_modules/express/lib/router/index.js:335:12)
    at next (node_modules/express/lib/router/index.js:275:10)
    at cookieParser (node_modules/cookie-parser/index.js:71:5)
```

**Comment by lreading** [comment]
I did not mean to close this with the comment on the ES6 refactor PR.  I need to be more careful with what words I use before linking an issue. :face_with_head_bandage: 

This will be done in 2.0

**Comment by lreading** [comment]
Closing as this is complete in v2
